const restaurantList = [
  {
    info: {
      id: "101",
      img: "/meghana.jpeg",
      name: "Meghana Foods",
      locality: "Narayanaguda",
      areaName: "Hyderabad",
      costForTwo: "₹500 for two",
      cuisines: ["Biryani", "North Indian"],
      avgRating: 3.9,
    },
  },
  {
    info: {
      id: "102",
      img: "/paradise.jpeg",
      name: "Paradise Biryani",
      locality: "Secunderabad",
      areaName: "Hyderabad",
      costForTwo: "₹700 for two",
      cuisines: ["Biryani", "Mughlai"],
      avgRating: 4.5,
    },
  },
  {
    info: {
      id: "103",
      img: "/bawarchi.jpeg",
      name: "Bawarchi",
      locality: "RTC X Roads",
      areaName: "Hyderabad",
      costForTwo: "₹600 for two",
      cuisines: ["Biryani", "Chinese"],
      avgRating: 4.7,
    },
  },
  {
    info: {
      id: "104",
      img: "/shahghouse.jpeg",
      name: "Shah Ghouse",
      locality: "Tolichowki",
      areaName: "Hyderabad",
      costForTwo: "₹700 for two",
      cuisines: ["Biryani", "Mughlai"],
      avgRating: 4.8,
    },
  },
  {
    info: {
      id: "105",
      img: "/pistahouse.jpeg",
      name: "Pista House",
      locality: "Charminar",
      areaName: "Hyderabad",
      costForTwo: "₹650 for two",
      cuisines: ["Biryani", "Haleem"],
      avgRating: 4.6,
    },
  },
  {
    info: {
      id: "106",
      img: "/kritunga.jpeg",
      name: "Kritunga",
      locality: "Kukatpally",
      areaName: "Hyderabad",
      costForTwo: "₹800 for two",
      cuisines: ["Andhra", "Biryani"],
      avgRating: 4.7,
    },
  },
  {
    info: {
      id: "107",
      img: "/chutneys.jpeg",
      name: "Chutneys",
      locality: "Banjara Hills",
      areaName: "Hyderabad",
      costForTwo: "₹550 for two",
      cuisines: ["South Indian"],
      avgRating: 4.8,
    },
  },
  {
    info: {
      id: "108",
      img: "/minerva.jpeg",
      name: "Minerva Coffee Shop",
      locality: "Himayatnagar",
      areaName: "Hyderabad",
      costForTwo: "₹500 for two",
      cuisines: ["South Indian", "Chinese"],
      avgRating: 4.5,
    },
  },
  {
    info: {
      id: "109",
      img: "/barbequenation.jpeg",
      name: "Barbeque Nation",
      locality: "Jubilee Hills",
      areaName: "Hyderabad",
      costForTwo: "₹1800 for two",
      cuisines: ["BBQ", "North Indian"],
      avgRating: 4.7,
    },
  },
  {
    info: {
      id: "110",
      img: "/absolutebbq.jpeg",
      name: "AB's - Absolute Barbecues",
      locality: "Gachibowli",
      areaName: "Hyderabad",
      costForTwo: "₹1700 for two",
      cuisines: ["BBQ", "Buffet"],
      avgRating: 4.8,
    },
  },
  {
    info: {
      id: "111",
      img: "/kfc.jpeg",
      name: "KFC",
      locality: "Madhapur",
      areaName: "Hyderabad",
      costForTwo: "₹600 for two",
      cuisines: ["Burger", "Fried Chicken"],
      avgRating: 4.3,
    },
  },
  {
    info: {
      id: "112",
      img: "/mcd.jpeg",
      name: "McDonald's",
      locality: "Hitech City",
      areaName: "Hyderabad",
      costForTwo: "₹500 for two",
      cuisines: ["Burger", "Fast Food"],
      avgRating: 4.2,
    },
  },
  {
    info: {
      id: "113",
      img: "/dominos.jpeg",
      name: "Domino's Pizza",
      locality: "Kondapur",
      areaName: "Hyderabad",
      costForTwo: "₹700 for two",
      cuisines: ["Pizza", "Italian"],
      avgRating: 4.4,
    },
  },
  {
    info: {
      id: "114",
      img: "/pizzahut.jpeg",
      name: "Pizza Hut",
      locality: "Miyapur",
      areaName: "Hyderabad",
      costForTwo: "₹850 for two",
      cuisines: ["Pizza", "Italian"],
      avgRating: 4.3,
    },
  },
  {
    info: {
      id: "115",
      img: "/burgerking.jpeg",
      name: "Burger King",
      locality: "Ameerpet",
      areaName: "Hyderabad",
      costForTwo: "₹450 for two",
      cuisines: ["Burger", "Fast Food"],
      avgRating: 4.2,
    },
  },
  {
    info: {
      id: "116",
      img: "/subway.jpeg",
      name: "Subway",
      locality: "Gachibowli",
      areaName: "Hyderabad",
      costForTwo: "₹500 for two",
      cuisines: ["Healthy Food", "Sandwich"],
      avgRating: 4.5,
    },
  },
  {
    info: {
      id: "117",
      img: "/starbucks.jpeg",
      name: "Starbucks",
      locality: "Jubilee Hills",
      areaName: "Hyderabad",
      costForTwo: "₹900 for two",
      cuisines: ["Cafe", "Coffee"],
      avgRating: 4.6,
    },
  },
  {
    info: {
      id: "118",
      img: "/creamstone.jpeg",
      name: "Cream Stone",
      locality: "Madhapur",
      areaName: "Hyderabad",
      costForTwo: "₹450 for two",
      cuisines: ["Desserts", "Ice Cream"],
      avgRating: 4.7,
    },
  },
  {
    info: {
      id: "119",
      img: "/naturals.jpeg",
      name: "Naturals Ice Cream",
      locality: "Banjara Hills",
      areaName: "Hyderabad",
      costForTwo: "₹350 for two",
      cuisines: ["Ice Cream", "Desserts"],
      avgRating: 4.8,
    },
  },
  {
    info: {
      id: "120",
      img: "/cafebahar.jpeg",
      name: "Cafe Bahar",
      locality: "Basheerbagh",
      areaName: "Hyderabad",
      costForTwo: "₹650 for two",
      cuisines: ["Biryani", "Chinese"],
      avgRating: 4.6,
    },
  },
];

export default restaurantList;